app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
  return view('home');
});
Route::resource('galleries', 'GalleriesController');
// Extra route to handle delete warning
Route::get('galleries/delete/{id}', 'GalleriesController@delete');
// Display flickr sites
Route::get('flickr', 'GalleriesController@flickr');
// Display tumblr sites
Route::get('tumblr', 'GalleriesController@tumblr');

// Extra route to provide alternate list of photos
Route::get('photos/list/{newOnly?}', 'PhotosController@listing');
// Extra route to display tumblr likes
Route::get('photos/likes', 'PhotosController@likes');
// Extra route to control index paging
Route::get('photos/display/{page?}', 'PhotosController@index');

Route::resource('photos', 'PhotosController');
// Extra route to handle delete warning
Route::get('photos/delete/{id}', 'PhotosController@delete');


Route::resource('submissions', 'SubmissionsController');
// Extra route to handle delete warning
Route::get('submissions/delete/{id}', 'SubmissionsController@delete');
// Extra route to handle creating submission from a photo
Route::get('submissions/create/{id}', 'SubmissionsController@create');

// Authentication routes
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Admin routes
Route::get('admin/index', 'AdminController@index');

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{

    protected $table = 'gallery';
    protected $fillable = [
    'name',
    'url',
    'ignore_this_site',
    'accepts_submissions',
    'reblog_posts',
    'approvals_only',
    'site_type'
  ];

  // relationships

  public function submission()
  {
      return $this->hasMany('App\Submission');
  }

    public function photos()
    {
        return $this->belongsToMany('App\Photo', 'submission')->withTimestamps();
    }

  // mutators

  public function getMembershipDateAttribute($value)
  {
      return convertToMMDDYYYY($value);
  }

    public function setMembershipDateAttribute($value)
    {
        $this->attributes['membership_date'] = convertToYYYYMMDD($value);
    }
}

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{

    protected $table = 'photo';
    protected $fillable = [
    'file_name',
    'url',
    'posted_date',
    'notes',
    'notes_last30',
    'notes_last10',
  ];

  // relationships

  public function submissions()
  {
      return $this->hasMany('App\Submission');
  }

    public function galleries()
    {
        return $this->belongsToMany('App\Gallery', 'submission')->withTimestamps();
    }

  // accessors and mutators

  public function getPostedDateAttribute($value)
  {
      return convertToMMDDYYYY($value);
  }

    public function setPostedDateAttribute($value)
    {
        $this->attributes['posted_date'] = convertToYYYYMMDD($value);
    }

    public function getCreatedAtAttribute($value)
    {
        return convertToMMDDYYYY($value);
    }

    public function getUpdatedAtAttribute($value)
    {
        return convertToMMDDYYYY($value);
    }

/*
  public function setNotesAttribute($value) {
    if (isset($this->attributes['other_notes'])) {
      $otherNotes = $this->attributes['other_notes'];
    }
    else {
      $otherNotes = 0;
    }
    $this->attributes['notes'] = $value;
    $this->attributes['total_notes'] = $value + $otherNotes;
  }

  public function setOtherNotesAttribute($value) {
    if (isset($this->attributes['notes'])) {
      $notes = $this->attributes['notes'];
    }
    else {
      $notes = 0;
    }
    $this->attributes['other_notes'] = $value;
    $this->attributes['total_notes'] = $value + $notes;
  }
  */
}

app/Http/Controllers/GalleriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Gallery;
use App\Submission;
use App\Http\Requests\GalleryRequest;

class GalleriesController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['only' => ['create', 'store', 'edit', 'update', 'delete', 'destroy']]);
    }

  /**
  * Display a listing of flickr sites.
  *
  * @return Response
  */
  public function flickr(Request $request)
  {
      $grids = $this->dispatchFrom('App\Jobs\CreateGalleriesGrid', $request,
    ['siteType' => 'flickr']);
      return view('galleries.index')->with([
      'narrowGrid' => $grids['narrowGrid'],
      'grid' => $grids['grid'],
      'pageTitle' => 'flickr'
    ]);
  }

  /**
  * Display a listing of tumblr sites.
  *
  * @return Response
  */
  public function tumblr(Request $request)
  {
      $grids = $this->dispatchFrom('App\Jobs\CreateGalleriesGrid', $request,
    ['siteType' => 'tumblr']);
      return view('galleries.index')->with([
      'narrowGrid' => $grids['narrowGrid'],
      'grid' => $grids['grid'],
      'pageTitle' => 'Tumblr'
    ]);
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return Response
  */
  public function create()
  {
      return view('galleries.create');
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  Request  $request
  * @return Response
  */
  public function store(GalleryRequest $request)
  {
      $siteType = $request->site_type;
      Gallery::create($request->all());
      flashMessage("The site has been added.", "alert-success");
      return redirect($siteType);
  }

  /**
  * Display the specified resource.
  *
  * @param  int  $id
  * @return Response
  */
  public function show($id)
  {
      $gallery = Gallery::findOrFail($id);
      $submissions = Submission::gallerySubmissions($id);
      $subCount = $gallery->reblogs;
      if ($subCount) {
          $grids = $this->dispatchFrom('App\Jobs\CreateSubmissionsGrid', new Request,
      ['submissions' => $submissions, 'page' => 'gallery']);
      } else {
          $noRecordsFound = 'No submissions for this gallery.';
          $grids['narrowGrid'] = $noRecordsFound;
          $grids['grid'] = $noRecordsFound;
      }
      return view('galleries.show')->with([
      'narrowGrid' => $grids['narrowGrid'],
      'grid' => $grids['grid'],
      'gallery' => $gallery,
      'submissions' => $submissions,
    ]);
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  int  $id
  * @return Response
  */
  public function edit($id)
  {
      $gallery = Gallery::findOrFail($id);
      return view('galleries.edit')->with('gallery', $gallery);
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  Request  $request
  * @param  int  $id
  * @return Response
  */
  public function update($id, Requests\GalleryRequest $request)
  {
      \Log::info($request);
      $gallery = Gallery::findOrFail($id);
      $gallery->update($request->all());
      flashMessage("The site has been updated.", "alert-success");
      return redirect('tumblr');
  }

    public function delete($id)
    {
        $gallery = Gallery::findOrFail($id);
        return view('galleries.delete')->with('gallery', $gallery);
    }

  /**
  * Remove the specified resource from storage.
  *
  * @param  int  $id
  * @return Response
  */
  public function destroy($id)
  {
      $gallery = Gallery::findOrFail($id);
      $name = $gallery->name;
      $gallery->delete();
      flashMessage("'$name' has been deleted.", "alert-success");
      return redirect('tumblr');
  }
}

resources/views/galleries/_form.blade.php
<?php
$siteTypeList = array(
  'flickr' => 'flickr',
  'tumblr' => 'tumblr'
);
?>


<div class="form-group">
  {!! Form::label('name', 'Name:') !!}
  {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
  {!! Form::label('url', 'Url:') !!}
  {!! Form::text('url', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
  {!! Form::label('site_type', 'Site Type:') !!}
  {!! Form::select('site_type', $siteTypeList, null, ['class' => 'form-control']) !!}
</div>


<div class="row">
  <div class="checkbox-line">
    <div class="col-md-3">
      {!! Form::hidden('accepts_submissions', false) !!}
      {!! Form::checkbox('accepts_submissions') !!} Accepts Submissions
    </div>
    <div class="col-md-3">
      {!! Form::hidden('reblog_posts', false) !!}
      {!! Form::checkbox('reblog_posts') !!} Will Reblog Posts
    </div>
    <div class="col-md-3">
      {!! Form::hidden('ignore_this_site', false) !!}
      {!! Form::checkbox('ignore_this_site') !!} Ignore
    </div>
    <div class="col-md-3">
      {!! Form::hidden('approvals_only', false) !!}
      {!! Form::checkbox('approvals_only') !!} Approvals Only
    </div>
  </div>
</div>

<div class="row">
  <div class="delete-buttons">
    <div class="col-sm-3 col-md-2">
      {!! Form::submit($submitButtonText, ['class' => 'btn btn-primary form-control']) !!}
    </div>
  </div>
</div>

resources/views/galleries/create.blade.php
@extends('app')

@section('pageTitle')

Add New Site

@stop

@section('pageClass') galleries-add-page @stop

@section('content')

  @include('errors.list')

  {!! Form::open(['url' => 'galleries']) !!}
    @include('galleries._form', ['submitButtonText' => 'Add Gallery'])
  {!! Form::close() !!}


@stop

resources/views/galleries/delete.blade.php
@extends('app')

@section('pageTitle')

Delete Site

@stop

@section('pageClass') galleries-delete-page @stop

@section('content')

  <h3>Do you really want to delete '{{$gallery->name}}'?</h3>

  <div class="row">
    <div class="delete-buttons">
      <div class="col-sm-3 col-md-2">
        {!! Form::open([
          'method' => 'DELETE',
          'action' => ['GalleriesController@destroy', $gallery->id]
        ]) !!}
          {!! Form::submit('Delete Gallery', ['class' => 'btn btn-primary btn-block']) !!}
        {!! Form::close() !!}
      </div>
      <div class="col-sm-3 col-md-2">
        {!! Form::open([
          'method' => 'GET',
          'action' => ['GalleriesController@index']
        ]) !!}
          {!! Form::submit('Cancel', ['class' => 'btn btn-primary btn-block']) !!}
        {!! Form::close() !!}
      </div>
    </div>
  </div>

@stop

resources/views/galleries/edit.blade.php
@extends('app')

@section('pageTitle')

Edit Sites

@stop

@section('pageClass') galleries-edit-page @stop

@section('content')

  @include('errors.list')

  {!! Form::model($gallery, [
    'method' => 'PATCH',
    'action' => ['GalleriesController@update', $gallery->id]
  ]) !!}
    @include('galleries._form', ['submitButtonText' => 'Update Site'])
  {!! Form::close() !!}


@stop

resources/views/galleries/index.blade.php
<?php
//Debugbar::info($galleries);
?>

@extends('app')

@section('pageTitle')

<?= $pageTitle  ?>

@stop

@section('pageClass') galleries-index-page @stop

@section('content')

<div class="content-galleries">
  <div class="visible-xs-block visible-sm-block">
     $narrowGrid ?>
  </div>
  <div class="visible-md-block visible-lg-block">
    <?= $grid ?>
  </div>
</div>
@stop

resources/views/galleries/show.blade.php
<?php
$ignore = showCheckMark($gallery->ignore_this_site);
$accepts_submissions = showCheckMark($gallery->accepts_submissions);
$reblog_posts = showCheckMark($gallery->reblog_posts);
$approvalsOnly = showCheckMark($gallery->approvals_only);

//$will_reblog = showCheckMark($gallery->will_reblog);
?>

@extends('app')

@section('pageTitle')

{{$gallery->name}}

@stop

@section('pageClass') galleries-show-page @stop

@section('content')

  <table class="table table-striped table-bordered">
    <tr>
      <th>Name</th>
      <th>Value</th>
    </tr>
    <tr>
      <td>ID</td>
      <td>{{$gallery->id}}</td>
    </tr>
    <tr>
      <td>Name</td>
      <td>{{$gallery->name}}</td>
    </tr>
    <tr>
      <td>Url</td>
      <td><a href="{{$gallery->url}}" target="_blank">{{$gallery->url}}</a></td>
    </tr>
    <tr>
      <td>Site Type</td>
      <td>{{$gallery->site_type}}</td>
    </tr>
    <tr>
      <td>Reblogs</td>
      <td>{{$gallery->reblogs}}</td>
    </tr>
    <tr>
      <td>Accepts Submissions</td>
      <td>{!!$accepts_submissions!!}</td>
    </tr>
    <tr>
      <td>Will Reblog Posts</td>
      <td>{!!$reblog_posts!!}</td>
    </tr>
    <tr>
      <td>Ignore This Site</td>
      <td>{!!$ignore!!}</td>
    </tr>
    <tr>
      <td>Approvals Only</td>
      <td>{!!$approvalsOnly!!}</td>
    </tr>
    <tr>
      <td>Created Date</td>
      <td>{{$gallery->created_at}}</td>
    </tr>
    <tr>
      <td>Updated Date</td>
      <td>{{$gallery->updated_at}}</td>
    </tr>
  </table>

  <br>
  <h3>Reblogs</h3>
  <div class="submissions-grid">
    <div class="visible-xs-block visible-sm-block submissions-grid">
      <?= $narrowGrid ?>
    </div>
    <div class="visible-md-block visible-lg-block submissions-grid">
      <?= $grid ?>
    </div>
  </div>
  @stop